# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeWhWZGvPFl7jd8Hd-cNNL_1Plp6ZG57
"""

import pandas as pd
import matplotlib.pyplot as plt

# -----------------------------
# Load data
# -----------------------------
df = pd.read_csv("Figure 5 Processed - Sheet1.csv")

# Convert date column
df["Rebalance Date"] = pd.to_datetime(df["Rebalance Date"])

# Set date as index (optional but clean)
df = df.set_index("Rebalance Date")

# -----------------------------
# Preview data
# -----------------------------
display(df)
print(df.describe())

# -----------------------------
# 1. Annual Returns Over Time
# -----------------------------
plt.figure()
plt.plot(df.index, df["Vol Target Ann Ret"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained Ann Ret"], label="Sharpe Constrained")
plt.title("Annual Returns Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Annual Return", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()

# -----------------------------
# 2. Annual Volatility Over Time
# -----------------------------
plt.figure()
plt.plot(df.index, df["Vol Target Ann Vol"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained Ann Vol"], label="Sharpe Constrained")
plt.title("Annual Volatility Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Annual Volatility", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()

# -----------------------------
# 3. Sharpe Ratios Over Time
# -----------------------------
plt.figure()
plt.plot(df.index, df["Vol Target Sharpe"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained Sharpe"], label="Sharpe Constrained")
plt.title("Sharpe Ratios Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Sharpe Ratio", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()

# -----------------------------
# 4. Maximum Drawdown Over Time
# -----------------------------
plt.figure()
plt.plot(df.index, df["Vol Target MaxDD"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained MaxDD"], label="Sharpe Constrained")
plt.title("Maximum Drawdown Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Max Drawdown", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()

# -----------------------------
# 5. Side-by-Side Comparison (Returns vs Risk)
# -----------------------------
plt.figure()
plt.scatter(df["Vol Target Ann Vol"], df["Vol Target Ann Ret"], label="Vol Target")
plt.scatter(df["Sharpe Constrained Ann Vol"], df["Sharpe Constrained Ann Ret"], label="Sharpe Constrained")
plt.title("Risk vs Return", fontsize=10)
plt.xlabel("Annual Volatility", fontsize=8)
plt.ylabel("Annual Return", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(18, 10)) # Adjust figure size for better readability

# 1. Annual Returns Over Time
plt.subplot(2, 3, 1) # 2 rows, 3 columns, 1st plot
plt.plot(df.index, df["Vol Target Ann Ret"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained Ann Ret"], label="Sharpe Constrained")
plt.title("Annual Returns Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Annual Return", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8, rotation=45)
plt.yticks(fontsize=8)

# 2. Annual Volatility Over Time
plt.subplot(2, 3, 2) # 2 rows, 3 columns, 2nd plot
plt.plot(df.index, df["Vol Target Ann Vol"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained Ann Vol"], label="Sharpe Constrained")
plt.title("Annual Volatility Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Annual Volatility", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8, rotation=45)
plt.yticks(fontsize=8)

# 3. Sharpe Ratios Over Time
plt.subplot(2, 3, 3) # 2 rows, 3 columns, 3rd plot
plt.plot(df.index, df["Vol Target Sharpe"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained Sharpe"], label="Sharpe Constrained")
plt.title("Sharpe Ratios Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Sharpe Ratio", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8, rotation=45)
plt.yticks(fontsize=8)

# 4. Maximum Drawdown Over Time
plt.subplot(2, 3, 4) # 2 rows, 3 columns, 4th plot
plt.plot(df.index, df["Vol Target MaxDD"], label="Vol Target")
plt.plot(df.index, df["Sharpe Constrained MaxDD"], label="Sharpe Constrained")
plt.title("Maximum Drawdown Over Time", fontsize=10)
plt.xlabel("Rebalance Date", fontsize=8)
plt.ylabel("Max Drawdown", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8, rotation=45)
plt.yticks(fontsize=8)

# 5. Side-by-Side Comparison (Returns vs Risk)
plt.subplot(2, 3, 5) # 2 rows, 3 columns, 5th plot
plt.scatter(df["Vol Target Ann Vol"], df["Vol Target Ann Ret"], label="Vol Target")
plt.scatter(df["Sharpe Constrained Ann Vol"], df["Sharpe Constrained Ann Ret"], label="Sharpe Constrained")
plt.title("Risk vs Return", fontsize=10)
plt.xlabel("Annual Volatility", fontsize=8)
plt.ylabel("Annual Return", fontsize=8)
plt.legend(fontsize=8)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)

plt.tight_layout() # Adjust layout to prevent overlapping titles/labels
plt.show()