# -*- coding: utf-8 -*-
"""researchpaper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iifg6Zjial2Aszfb5qF5V5BSpyjG-2v_
"""

# Block: DATA DOWNLOAD + BASIC CLEANING
# Run in Jupyter/VSCode. Requires: pip install yfinance arch scipy pandas numpy matplotlib statsmodels

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta

# ---------- USER INPUT ----------
# Replace or extend this list with the assets you want to monitor
TICKERS = ["SPY","QQQ","TLT","LQD","HYG","VNQ","GLD","BTC-USD"]  # example balanced universe
MARKET_TICKER = "SPY"      # market proxy for Treynor
RISK_FREE_RATE = 0.02      # annual risk-free (use live T-bill yield for production)
END_DATE = pd.Timestamp.today().normalize()
START_DATE = END_DATE - pd.DateOffset(years=5)  # last 5 years

# ---------- DOWNLOAD ----------
raw = yf.download(list(set(TICKERS + [MARKET_TICKER])),
                  start=START_DATE.strftime("%Y-%m-%d"),
                  end=END_DATE.strftime("%Y-%m-%d"),
                  auto_adjust=True, progress=False)

prices = raw.get('Close', raw).copy()
prices = prices.dropna(axis=1, how='all').ffill().dropna(how='all')
volumes = raw.get('Volume', None)
if volumes is not None:
    volumes = volumes[prices.columns].copy().ffill()

# ---------- RETURNS ----------
rets = prices.pct_change().dropna()   # daily simple returns
logrets = np.log(prices).diff().dropna()  # if you want log returns (for arch use often %*100)

# quick sanity
print("Data range:", prices.index.min().date(), "->", prices.index.max().date())
print("Tickers used:", list(prices.columns))
print("Price shape:", prices.shape)

# Block A: static metrics over the full 5-year window
import statsmodels.api as sm

def ann_sharpe(ret_series, rf=RISK_FREE_RATE):
    r = ret_series.dropna()
    excess_ann = r.mean() * 252 - rf
    vol_ann = r.std() * np.sqrt(252)
    return excess_ann / (vol_ann + 1e-12)

def ann_vol(ret_series):
    return ret_series.dropna().std() * np.sqrt(252)

def compute_beta(asset_rets, market_rets):
    df = pd.concat([asset_rets, market_rets], axis=1).dropna()
    if df.shape[0] < 60:
        return np.nan
    y = df.iloc[:,0].values
    x = sm.add_constant(df.iloc[:,1].values)
    model = sm.OLS(y, x).fit()
    return model.params[1]

def max_drawdown(price_series):
    curve = (price_series / price_series.iloc[0])
    peak = curve.cummax()
    dd = curve / peak - 1
    return dd.min()

market_rets = rets[MARKET_TICKER]

rows = []
for t in prices.columns:
    if t == MARKET_TICKER: continue
    r = rets[t]
    rows.append({
        "Ticker": t,
        "Sharpe(ann)": ann_sharpe(r),
        "AnnVol": ann_vol(r),
        "Beta": compute_beta(r, market_rets),
        "Treynor": (r.mean()*252 - RISK_FREE_RATE) / (compute_beta(r, market_rets) + 1e-12),
        "MaxDD": max_drawdown(prices[t]),
        "TotalROI": prices[t].iloc[-1] / prices[t].iloc[0] - 1
    })

metrics_df = pd.DataFrame(rows).set_index("Ticker").sort_values("Sharpe(ann)", ascending=False)
metrics_df.round(4)

pip install arch

# Block B: GARCH(1,1) fits (using arch package)
from arch import arch_model

garch_results = {}
forecast_horizon_days = 5

for t in prices.columns:
    # use daily percentage returns for GARCH (scale *100 for arch)
    r = (prices[t].pct_change().dropna() * 100).dropna()
    if len(r) < 250:  # need enough obs
        garch_results[t] = {"model": None, "cond_vol_ann": np.nan, "fc_vol_ann": np.nan}
        continue
    am = arch_model(r, vol='Garch', p=1, q=1, mean='Zero', dist='normal')
    try:
        res = am.fit(disp='off')
    except Exception as e:
        garch_results[t] = {"model": None, "cond_vol_ann": np.nan, "fc_vol_ann": np.nan}
        continue
    # last conditional volatility (in percent), convert to decimal and annualize
    cond_vol_pct = res.conditional_volatility.iloc[-1]    # percent
    cond_vol_daily = cond_vol_pct / 100.0
    cond_vol_ann = cond_vol_daily * np.sqrt(252)
    # forecast 1-day ahead variance, convert to vol annualized
    fc = res.forecast(horizon=forecast_horizon_days, reindex=False)
    try:
        var_1 = fc.variance.values[-1, 0]    # percent^2
        vol_1_daily = np.sqrt(var_1) / 100.0
        vol_1_ann = vol_1_daily * np.sqrt(252)
    except Exception:
        vol_1_ann = np.nan

    garch_results[t] = {"model": res, "cond_vol_ann": cond_vol_ann, "fc_vol_ann": vol_1_ann}

# Create a DataFrame summary
garch_df = pd.DataFrame({k: {"cond_vol_ann": v["cond_vol_ann"], "fc_vol_ann": v["fc_vol_ann"]}
                         for k,v in garch_results.items()}).T
garch_df.round(4)

# Block C: VaR and CVaR (95%)
def hist_var(r, p=0.95):
    return -np.percentile(r.dropna(), (1-p)*100)

def hist_cvar(r, p=0.95):
    cutoff = np.percentile(r.dropna(), (1-p)*100)
    tail = r[r <= cutoff]
    return -tail.mean() if len(tail) > 0 else np.nan

var_rows = []
for t in prices.columns:
    r = rets[t].dropna()
    var_95_daily = hist_var(r, 0.95)
    cvar_95_daily = hist_cvar(r, 0.95)
    var_rows.append({
        "Ticker": t,
        "VaR95_daily": var_95_daily,
        "CVaR95_daily": cvar_95_daily,
        "VaR95_ann_approx": var_95_daily * np.sqrt(252),
        "CVaR95_ann_approx": cvar_95_daily * np.sqrt(252)
    })
var_df = pd.DataFrame(var_rows).set_index("Ticker").sort_values("VaR95_daily")
var_df.round(6)

# Block D: allocation helpers

import cvxpy as cp   # if cvxpy not available, the fallback uses scipy.minimize
from scipy.optimize import minimize

def vol_target_weights(ann_vols, target_vol=0.08):
    """
    Simple volatility targeting by risk parity-ish scaling:
    w_i proportional to 1/vol_i then scaled so portfolio vol == target_vol.
    This results in lower weights for high-vol assets.
    """
    inv = 1.0 / (ann_vols + 1e-12)
    w_raw = inv / np.nansum(inv)
    # scale to reach target volatility: portfolio vol = sqrt(w' Sigma w)
    # we approximate Sigma by (ann_vols^2) when off-diagonals unknown -> conservative
    # Better: compute full covariance when available.
    return pd.Series(w_raw, index=ann_vols.index)

def optimize_sharpe_with_constraints(mu, cov, vol_cap=None, cvar_cap=None):
    """
    Maximize Sharpe (mu' w - rf) / sqrt(w' cov w) subject to w >=0, sum(w)=1,
    and optional vol cap (sqrt(w'cov w) <= vol_cap). cvar_cap omitted for simplicity (needs scenario-based).
    """
    n = len(mu)
    x0 = np.ones(n) / n
    bounds = [(0,1)]*n
    cons = ({"type":"eq","fun": lambda w: np.sum(w)-1},)
    if vol_cap is not None:
        cons = cons + ({"type":"ineq", "fun": lambda w, cov=cov, vol_cap=vol_cap: vol_cap - np.sqrt(w @ cov @ w)},)
    def neg_sharpe(w, mu=mu, cov=cov):
        num = np.dot(w, mu) - RISK_FREE_RATE
        den = np.sqrt(w @ cov @ w) + 1e-12
        return - num / den
    res = minimize(neg_sharpe, x0, bounds=bounds, constraints=cons, method="SLSQP", options={"maxiter":500})
    w = res.x if res.success else x0
    w = np.clip(w, 0, 1)
    return w / w.sum()

# Example compute mu and cov from recent lookback window
lookback_days = 252 * 2  # 2-year lookback
recent = rets.iloc[-lookback_days:]
mu = recent.mean() * 252
cov = recent.cov() * 252

ann_vols = recent.std() * np.sqrt(252)
w_voltarget = vol_target_weights(ann_vols, target_vol=0.08)
w_sharpe_constrained = pd.Series(optimize_sharpe_with_constraints(mu[ann_vols.index].values, cov.loc[ann_vols.index, ann_vols.index].values, vol_cap=0.12),
                                 index=ann_vols.index)

print("Vol-target weights (pro-rated):\n", w_voltarget.round(4))
print("Constrained Sharpe weights:\n", w_sharpe_constrained.round(4))

# Block E: walk-forward backtest skeleton (quarterly rebalance)
rebalance_dates = rets.resample("Q").last().index
results = []

for i, t in enumerate(rebalance_dates[:-1]):
    train_start = t - pd.DateOffset(years=2)
    train_end = t - pd.Timedelta(days=1)
    train = rets.loc[train_start:train_end].dropna(axis=1, how='all')
    if len(train) < 252:
        continue

    # compute inputs
    mu = train.mean() * 252
    cov = train.cov() * 252
    ann_vols = train.std() * np.sqrt(252)

    # compute allocations
    wt_vol = vol_target_weights(ann_vols)
    wt_sharpe = pd.Series(optimize_sharpe_with_constraints(mu.values, cov.values, vol_cap=0.12), index=mu.index)

    # next period returns (apply from t to next rebalance)
    next_t = rebalance_dates[i+1]
    period_rets = rets.loc[t:next_t].dropna(axis=1, how='all')

    # align weights to available assets in period_rets
    wt_vol_aligned = wt_vol.reindex(period_rets.columns).fillna(0)
    wt_vol_aligned = wt_vol_aligned / wt_vol_aligned.sum()

    wt_sharpe_aligned = wt_sharpe.reindex(period_rets.columns).fillna(0)
    wt_sharpe_aligned = wt_sharpe_aligned / wt_sharpe_aligned.sum()

    port_vol_returns = (period_rets * wt_vol_aligned).sum(axis=1)
    port_sharpe_returns = (period_rets * wt_sharpe_aligned).sum(axis=1)

    # realized metrics
    def port_stats(pr):
        ann_ret = (1+pr).prod() ** (252/len(pr)) - 1
        ann_vol = pr.std() * np.sqrt(252)
        sharpe = (pr.mean()*252 - RISK_FREE_RATE)/(ann_vol + 1e-12)
        maxdd = (1+pr).cumprod().div((1+pr).cumprod().cummax()).min() - 1
        return ann_ret, ann_vol, sharpe, maxdd

    vol_stats = port_stats(port_vol_returns)
    sharpe_stats = port_stats(port_sharpe_returns)

    # fault checks: compare realized vol for each asset in period to GARCH fc from train
    faults = []
    for a in period_rets.columns:
        # predicted (1-day ahead annualized) vol from GARCH fit on train
        g = garch_results.get(a, {})
        pred = g.get("fc_vol_ann", np.nan)
        realized = period_rets[a].std() * np.sqrt(252)
        if pd.notna(pred) and pd.notna(realized) and pred > 0 and realized > 2.0 * pred:
            faults.append({"asset": a, "pred_vol": pred, "real_vol": realized, "ratio": realized/pred})

    results.append({
        "rebalance": t,
        "wt_vol": wt_vol_aligned,
        "wt_sharpe": wt_sharpe_aligned,
        "vol_stats": vol_stats,
        "sharpe_stats": sharpe_stats,
        "faults": faults,
        "period_rets_index": period_rets.index
    })

# Aggregate performance curves for the whole backtest
def concat_ports(series_list):
    if not series_list: return pd.Series(dtype=float)
    return pd.concat(series_list).sort_index()

vol_port_daily = concat_ports([ (rets.loc[r["period_rets_index"], :] * r["wt_vol"]).sum(axis=1) for r in results ])
# Simplify: build cumulative by re-summing per-period returns
vol_curves = []
sh_curves = []
for r in results:
    pr_vol = (rets.loc[r["period_rets_index"], r["wt_vol"].index] * r["wt_vol"]).sum(axis=1)
    pr_sh = (rets.loc[r["period_rets_index"], r["wt_sharpe"].index] * r["wt_sharpe"]).sum(axis=1)
    vol_curves.append((1+pr_vol).cumprod())
    sh_curves.append((1+pr_sh).cumprod())

# Concatenate piecewise:
if vol_curves:
    vol_full = pd.concat(vol_curves).sort_index()
else:
    vol_full = pd.Series(dtype=float)
if sh_curves:
    sh_full = pd.concat(sh_curves).sort_index()
else:
    sh_full = pd.Series(dtype=float)

results.append({
    "rebalance": t,
    "wt_vol": wt_vol_aligned,
    "wt_sharpe": wt_sharpe_aligned,
    "vol_stats": vol_stats,
    "sharpe_stats": sharpe_stats,
    "faults": faults,
    "period_rets_index": period_rets.index
})

df = pd.DataFrame({
    "Rebalance Date": [r["rebalance"] for r in results],
    "Vol Target Ann Ret": [r["vol_stats"][0] for r in results],
    "Vol Target Ann Vol": [r["vol_stats"][1] for r in results],
    "Vol Target Sharpe": [r["vol_stats"][2] for r in results],
    "Vol Target MaxDD": [r["vol_stats"][3] for r in results],
})

import pandas as pd

summary_data = []
for r in results:
    summary_data.append({
        "Rebalance Date": r["rebalance"],
        "Vol Target Ann Ret": r["vol_stats"][0],
        "Vol Target Ann Vol": r["vol_stats"][1],
        "Vol Target Sharpe": r["vol_stats"][2],
        "Vol Target MaxDD": r["vol_stats"][3],
        "Sharpe Constrained Ann Ret": r["sharpe_stats"][0],
        "Sharpe Constrained Ann Vol": r["sharpe_stats"][1],
        "Sharpe Constrained Sharpe": r["sharpe_stats"][2],
        "Sharpe Constrained MaxDD": r["sharpe_stats"][3],
    })

summary_df = pd.DataFrame(summary_data).set_index("Rebalance Date")
display(summary_df.round(4))

from matplotlib import pyplot as plt
_df_23['Vol Target MaxDD'].plot(kind='line', figsize=(8, 4), title='Vol Target MaxDD')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_22['Vol Target Sharpe'].plot(kind='line', figsize=(8, 4), title='Vol Target Sharpe')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_21['Vol Target Ann Vol'].plot(kind='line', figsize=(8, 4), title='Vol Target Ann Vol')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_20['Vol Target Ann Ret'].plot(kind='line', figsize=(8, 4), title='Vol Target Ann Ret')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_0['Vol Target Ann Ret'].plot(kind='hist', bins=20, title='Vol Target Ann Ret')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Vol Target Ann Vol'].plot(kind='hist', bins=20, title='Vol Target Ann Vol')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Vol Target Sharpe'].plot(kind='hist', bins=20, title='Vol Target Sharpe')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Vol Target MaxDD'].plot(kind='hist', bins=20, title='Vol Target MaxDD')
plt.gca().spines[['top', 'right',]].set_visible(False)

!python --version